### ISSUE TITLE
Compilation failures

### ISSUE THREAD

**Issue by catb0t** [sparist/Om#24]
I fixed a few compiler errors in a branch: https://github.com/sparist/Om/compare/master...catb0t:test: 
- returning `*this` from things like `void Om::Sink::ContainerFrontSink< ThisItem, ThisContainer >::Swap (ContainerFrontSink & theContainerFrontSink)` which must be unintended
- my `clang 9.0` doesn't have an `-Wno-unneeded-internal-declaration` option, so removed from CMakeLists
- `std::auto_ptr` is deprecated, but `std::unique_ptr` is not a drop-in replacement, and there are many uses of `auto_ptr`, so `-Wno-deprecated-declarations` added to CMakeLists

However, I'm not familiar enough with Om's C++ objects to know the correct fix for:

https://github.com/sparist/Om/blob/e3b76ee4fda0a56d0a0208b601e65449bfdd4b07/code/om/source/code_point_source.cpp#L142-L156

The last call to `boost::swap` gives `error: no matching function for call to ‘swap(Om::CodePoint&, Om::CodePoint&)’`, and there's a similar problem with `om/code/om/source/code_point_string_back_source.cpp:380:2: error: no matching function for call to ‘swap(std::string&, std::string&)’`.

**Comment by sparist** [comment]
Thanks for finding these! I have a full work-in-progress rewrite of Om on my computer but haven't pushed anything yet. In the meantime, I'll take a look at fixing these.

**Comment by catb0t** [comment]
I'm very happy to hear about a WIP rewrite! and thanks.

**Comment by sparist** [comment]
I've fixed the bit rot in master and I believe I've included all of your fixes, along with several others that were necessary to make it build on Xcode and MSVC 2019.

Thanks again for bringing this stuff to my attention, and sorry for the delay in the fixes. Please let me know if there are further issues.

**Comment by catb0t** [comment]
Thank you so much! This is awesome, I can finally test against the reference implementation.
