### ISSUE TITLE
Does Om currently evaluate from left-to-right or right-to-left? 

### ISSUE THREAD

**Issue by catb0t** [sparist/Om#25]
I couldn't tell from trying to read the source code: does Om evaluate `{ define {X {Y}} {X} }` in that order, or backwards as 
```
{X}
{X {Y}}
define
```
?

From my experience trying, evaluating end-to-beginning makes naive partiality easier and simplifies some other things, but it also introduces other issues like name binding (which must be postponed), that are probably solved by doing it correctly, evaluating left-to-right.

**Comment by sparist** [comment]
It always evaluates from left to right.

(Sorry for the late response!)
